sudo: false
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

notifications:
  email: false

env:
    - TOXENV=py36
    - TOXENV=py37
    - TOXENV=py38
    - TOXENV=docs

install:
    - pip install -U tox-travis codecov

script: tox

after_success:
  - codecov
