sudo: false
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

notifications:
  email: false

install:
    - pip install -U tox-travis codecov

script:
  - tox
  - codecov

after_success:
  - codecov
