# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
 repositories:
   - repository: cielquan
     type: github
     endpoint: github
     name: cielquan/azure-pipelines-template
     ref: master

jobs:
- template: run-tox.yml@cielquan
  parameters:
    checkout_submodules: false
    tox_version: ''
    configs:
      test:
        tox_envs: [py39, doc]
        os: [linux]
        architectures: [x64, x86]
      test_win:
        tox_envs: [py37]
        os: windows
        architectures: [x64, x86]
