name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  batch: true
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']
  paths:
    exclude:
    - readthedocs.yml
    - LICENSE.txt
    - .gitignore
    - .gitattributes
    - .github/*

pr:
  branches:
    include: [master, development]

resources:
  repositories:
    - repository: cielquan
      type: github
      endpoint: github
      name: cielquan/azure-pipelines-template
      ref: test-codeclimate-cov  # CHANGE ME

variables:
  "System.PreferGit": true
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://toxdev.visualstudio.com/tox/_build/results?buildId=$(Build.BuildId)"
  GIT_BRANCH: $(Build.SourceBranch)
  GIT_COMMIT_SHA: $(Build.SourceVersion)
  PYTEST_ADDOPTS: "-v -v -ra --showlocals"
  PYTEST_XDIST_N: '0'

jobs:
  - template: jobs/run-tox.yml@cielquan
    parameters:
      tox_envs:
#        pre-commit:
#          display_name: pre_commit
#        safety: null
        py36:
          os: [linux, windows, macOs]
#        py37:
#          os: [linux, windows, macOs]
#        py38:
#          os: [linux, windows, macOs]
#        py39: null
#        pypy3:
#          os: [linux, macOs]
#        package:
#          os: [linux, windows, macOs]
#        docs-test-html:
#          display_name: docs_test_html
#        docs-test-linkcheck:
#          display_name: docs_test_linkcheck
#        docs-test-coverage:
#          display_name: docs_test_coverage
#        docs-test-doctest:
#          display_name: docs_test_doctest
      coverage:
        with_toxenv: 'coverage'
        for_envs: [py36]
#        for_envs: [py36, py37, py38, py39, pypy3]
      send_cov_to_codeclimate: true

  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
    - template: jobs/publish-pypi-poetry.yml@cielquan
      parameters:
        custom_repository: true
        dependsOn:
#           - pre_commit
          - safety
#           - package
# #           - dev
#           - py36
#           - py37
#           - py38
#           - py39
#           - pypy3
#           - report_coverage
# #           - docs_test_html
# #           - docs_test_linkcheck
# #           - docs_test_coverage
# #           - docs_test_doctest
