# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: cielquan
      type: github
      endpoint: github
      name: cielquan/azure-pipelines-template
      ref: master

jobs:
- template: run-tox.yml@cielquan
  parameters:
    tox_version: '3.15.0'
    tox_python: '3.7'
    checkout_submodules: true
    default_python: '3.7'
    tox_envs:
      py37:
        os: [linux, windows, macOs]
      py36:
        os: [linux, windows, macOs]
      py38:
        os: [linux, windows, macOs]
    coverage:
      with_toxenv: 'coverage'
      for_envs: [py37, py36, py38]
