[build-system]
requires = [
    "setuptools >= 42",
    "setuptools_scm[toml] >= 3.4, <4",
    "wheel >= 0.34",
]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
write_to = "src/python_test/version.py"
write_to_template = "__version__ = {version!r}"

[tool.poetry]
name = "python_test"
version = "0.3.0"
description = "test stufff"
authors = ["Cielquan <cielquan@protonmail.com>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/Cielquan/python_test"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.6.1"
toml = {version = "^0.10.1", optional = true}
pytest = {version = "^5.4.2", optional = true}
pytest-cov = {version = "^2.8.1", optional = true}
sphinx = {version = "^2", optional = true}
sphinx-rtd-theme = {version = "^0.4", optional = true}
pre-commit = {version = "^2.4", optional = true}
mypy = {version = "0.770", optional = true}
pylint = {version = "^2.4", optional = true}

[tool.poetry.dev-dependencies]
devtools = {version = "^0.5", extras = ["pygments"]}

[tool.poetry.extras]
testing = ["pytest", "pytest-cov", "toml"]
docs = ["sphinx", "sphinx-rtd-theme"]
pre-commit = ["pre-commit", "mypy", "pylint"]


# -- TOWNCRIER CONFIG ----------------------------------------------------------------------
[tool.towncrier]
package = "python_test"
package_dir = "src"
# single_file = true  # if false, filename is formatted like `title_format`.
filename = "CHANGELOG_auto.rst"
directory = "docs/.changelog"
template = "docs/.changelog/template.jinja2"
# start_line = "start of generated content"
title_format = "v{version} ({project_date})"
issue_format = "`#{issue} <https://github.com/tox-dev/tox/issues/{issue}>`_"
underlines = ["-", "~"]
wrap = false  # Wrap text to 79 characters
all_bullets = true  # make all fragments bullet points

[[tool.towncrier.type]]
directory = "deprecation"
name = "Deprecations (removal in next major release)"
showcontent = true

[[tool.towncrier.type]]
directory = "breaking"
name = "Backward incompatible changes"
showcontent = true

[[tool.towncrier.type]]
directory = "misc"
name = "Miscellaneous"
showcontent = true

[[tool.towncrier.section]]
path = ""


# -- BLACK CONFIG ----------------------------------------------------------------------
[tool.black]
line-length = 88
exclude = "venv/"


# -- ISORT CONFIG ----------------------------------------------------------------------
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
known_first_party = ["python_test", "tests"]
known_third_party = ["setuptools", "sphinx_rtd_theme"]
skip = ["venv"]


# -- PYTEST CONFIG ---------------------------------------------------------------------
# support for pyproject.toml for 5.5 planned
#[tool.pytest]
#addopts = ["-ra", "--showlocals"]
#mock_use_standalone_module = true


# -- COVERAGE CONFIG -------------------------------------------------------------------
[tool.coverage.run]
branch = true
parallel = true
source = ["src/"]
[tool.coverage.report]
fail_under = 100
skip_covered = false
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "def __str__",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
]
omit = [
    "venv/*",
    "tests/*",
    "setup.py",
    "*/__main__.py",
]
[tool.coverage.paths]
source = [
    "src/python_test",
     "*/.tox/*/lib/python*/site-packages/python_test",
     "*/.tox/pypy*/site-packages/python_test",
     "*/.tox\\*\\Lib\\site-packages\\python_test",
     "*/src/python_test",
     "*\\src\\python_test",
]


# -- PYLINT CONFIG ---------------------------------------------------------------------
[tool.pylint."MESSAGES CONTROL"]
disable = [
    "C0330", # Indentation | deactivated for black
#        print-statement, #E1601
#        parameter-unpacking, #E1602
#        unpacking-in-except, #E1603
#        old-raise-syntax, #E1604
#        backtick, #E1605
#        long-suffix, #E1606
#        old-ne-operator, #E1607
#        old-octal-literal, #E1608
#        import-star-module-level, #E1609
#        non-ascii-bytes-literal, #E1610
#        raw-checker-failed, ##I0001
#        bad-inline-option, ##I0010
#        locally-disabled, ##I0011
#        file-ignored, ##I0013
#        suppressed-message, ##I0020
#        useless-suppression, ##I0021
#        deprecated-pragma, ##I0022
#        use-symbolic-message-instead, #I0023
#        apply-builtin, #W1601
#        basestring-builtin, #W1602
#        buffer-builtin, #W1603
#        cmp-builtin, #W1604
#        coerce-builtin, #W1605
#        execfile-builtin, #W1606
#        file-builtin, #W1607
#        long-builtin, #W1608
#        raw_input-builtin, #W1609
#        reduce-builtin, #W1610
#        standarderror-builtin, #W1611
#        unicode-builtin, #W1612
#        xrange-builtin, #W1613
#        coerce-method, #W1614
#        delslice-method, #W1615
#        getslice-method, #W1616
#        setslice-method, #W1617
#        no-absolute-import, #W1618
#        old-division, #W1619
#        dict-iter-method, #W1620
#        dict-view-method, #W1621
#        next-method-called, #W1622
#        metaclass-assignment, #W1623
#        indexing-exception, #W1624
#        raising-string, #W1625
#        reload-builtin, #W1626
#        oct-method, #W1627
#        hex-method, #W1628
#        nonzero-method, #W1629
#        cmp-method, #W1630
#        input-builtin, #W1632
#        round-builtin, #W1633
#        intern-builtin, #W1634
#        unichr-builtin, #W1635
#        map-builtin-not-iterating, #W1636
#        zip-builtin-not-iterating, #W1637
#        range-builtin-not-iterating, #W1638
#        filter-builtin-not-iterating, #W1639
#        using-cmp-argument, #W1640
#        eq-without-hash, #W1641
#        div-method, #W1642
#        idiv-method, #W1643
#        rdiv-method, #W1644
#        exception-message-attribute, #W1645
#        invalid-str-codec, #W1646
#        sys-max-int, #W1647
#        bad-python3-import, #W1648
#        deprecated-string-function, #W1649
#        deprecated-str-translate-call, #W1650
#        deprecated-itertools-function, #W1651
#        deprecated-types-field, #W1652
#        next-method-defined, #W1653
#        dict-items-not-iterating, #W1654
#        dict-keys-not-iterating, #W1655
#        dict-values-not-iterating, #W1656
#        deprecated-operator-function, #W1657
#        deprecated-urllib-function, #W1658
#        xreadlines-attribute, #W1659
#        deprecated-sys-function, #W1660
#        exception-escape, #W1661
#        comprehension-escape, #W1662
#        C0330,
#        F0010,
]


# -- FLAKE8 CONFIG ---------------------------------------------------------------------
#: Currently not supported - settings set via CLI call in .pre-commit-config.yaml
#[tool.flake8]
#count = true
#statistics = true
#extend-exclude = [
#    "*venv*/",
#    "*.egg",
#    "build/"
#]
#extend-ignore = ["E203"]
#max-line-length = 88
#max-complexity = 20
#pytest-fixture-no-parentheses = true
#format = "${cyan}%(path)s${reset}:${yellow_bold}%(row)d${reset}:${green_bold}%(col)d${reset}: ${red_bold}%(code)s${reset} %(text)s"
