[build-system]
    requires = ["poetry>=0.12"]
    build-backend = "poetry.masonry.api"


#: -- ADDITIONAL METADATA POETRY DOES NOT HOLD -----------------------------------------
[tool._metadata]
    first_release_year = 2019


#: -- POETRY CONFIG --------------------------------------------------------------------
[tool.poetry]
    name = "python_test_cielquan"
    version = "0.5.15"
    description = "test stufff"
    authors = ["Cielquan <cielquan@protonmail.com>"]
    license = "GPL-3.0-or-later"
    repository = "https://github.com/Cielquan/python_test-cielquan"
    readme = "README.rst"
    packages = [
        { include = "python_test_cielquan", from = "src" },
    ]

    [tool.poetry.dependencies]
        python = "^3.6.1"
        importlib-metadata = {version = ">=1.6, <3.0", python = "<3.8"}
        #: Testing
        pytest = {version = "^6", optional = true}
        pytest-xdist = {version = "^1.34", optional = true}
        pytest-cov = {version = "^2.10", optional = true}
        coverage = {extras = ["toml"], version = "^5.2.1", optional = true}
        coverage-conditional-plugin = {version = "^0.3.1", optional = true}
        pytest-sugar = {version = "^0.9.4", optional = true}
        pytest-randomly = {version = "^3.4", optional = true}
#        pytest-mock = {version = "^3.2.0", optional = true}
#        mock = {version = "^4.0.2", optional = true}
#        faker = {version = "^4.1.1", optional = true}
#        pytest-factoryboy = {version = "^2.0.3", optional = true}
#        pytest-benchmark = {version = "^3.2.3", optional = true}
#        pytest-profiling = {version = "^1.7.0", optional = true}
#        pytest-bdd = {version = "^3.3.0", optional = true}
#        behave = {version = "^1.2.6", optional = true}
        #: Docs
        sphinx = {version = "^3.1", optional = true}
        m2r2 = {version = "^0.2.7", optional = true}
        sphinx-autobuild = {version = "^0.7.1", optional = true}
        formelsammlung = {version = "^3.0.1", optional = true}  #: Also for pre-commit, nox
        python-dotenv = {version = "^0.14.0", optional = true}
        sphinx-rtd-theme = {version = "^0.5", optional = true}
        sphinx-autodoc-typehints = {version = "^1.10.3", optional = true}
        sphinxcontrib-apidoc = {version = "^0.3.0", optional = true}
        sphinxcontrib-spelling = {version = "^7.1.0", optional = true}
#        sphinx-click = {version = "^2.3.2", optional = true}
#        sphinxcontrib-confluencebuilder = {version = "^1.2.0", optional = true}
        # sphinxcontrib-confluencebuilder = {git = "https://github.com/sphinx-contrib/confluencebuilder.git", rev = "6e6edbb64260ea09858eb844dd46c79c7697267e", optional = true}
        #: Code check
        pre-commit = {version = "^2.4", optional = true}
        rstcheck = { git = "https://github.com/myint/rstcheck.git", rev = "3f92957478422df87bd730abde66f089cc1ee19b", optional = true}
        mypy = {version = "0.790", optional = true}
        #: flakehell & flake8-plugins
        pylint = {version = "^2.5.3", optional = true}
        pyenchant = {version = "^3.1.1", optional = true}
        flakehell = {version = "^0.7.0", optional = true}
        flake8 = {version = "^3.8.4", optional = true}
        pydocstyle = {version = "^5.1.1", optional = true}
        pep8-naming = {version = "^0.11.1", optional = true}
        flake8-2020 = {version = "^1.6.0", optional = true}
        flake8-aaa = {version = "^0.11.0", optional = true}
        flake8-annotations = {version = "^2.4.1", optional = true}
        flake8-bandit = {version = "^2.1.2", optional = true}
        bandit = {version = "^1.6.2", optional = true}
        flake8-broken-line = {version = "^0.3.0", optional = true}
        flake8-bugbear = {version = "^20.1.4", optional = true}
        flake8-cognitive-complexity = {version = "^0.1.0", optional = true}
        flake8-comprehensions = {version = "^3.3.0", optional = true}
        flake8-docstrings = {version = "^1.5.0", optional = true}
        flake8-eradicate = {version = "^1.0.0", optional = true}
        flake8-logging-format = {version = "^0.6.0", optional = true}
        flake8-mutable = {version = "^1.2.0", optional = true}
        flake8-no-u-prefixed-strings = {version = "^0.2", optional = true}
        flake8-pytest-style = {version = "^1.3.0", optional = true}
        flake8-rst-docstrings = {version = "^0.0.14", optional = true}
        flake8-simplify = {version = "^0.9.1", optional = true}
        flake8-sql = {version = "^0.4.1", optional = true}
        flake8-string-format = {version = "^0.3.0", optional = true}
        flake8-typing-imports = {version = "^1.10.0", optional = true}
        flake8-use-fstring = {version = "^1.1", optional = true}
        flake8-variables-names = {version = "^0.0.3", optional = true}
        flake8-walrus = {version = "^1.1.0", python = ">=3.8", optional = true}
        #: nox env dependencies
        nox = {version = "^2020.8.22", optional = true}
        tox = {version = "^3.20.1", optional = true}
        tomlkit = {version = ">=0.7.0, <1.0.0", optional = true}
        poetry = {version = "^1.1.4", optional = true}
        twine = {version = "^3.2.0", optional = true}
        safety = {version = "^1.9.0", optional = true}
        diff-cover = {version = "^4.0.1", optional = true}
        # Additional tools
#        python-semantic-release = {version = "^7.3.0", optional = true}

    [tool.poetry.dev-dependencies]
        nox = "*"  #: Version managed above
        tomlkit = "*"  #: Version managed above
        formelsammlung = "*"  #: Version managed above
        poetry = "*"  #: Version managed above
        devtools = {version = "^0.6", extras = ["pygments"]}
        ipython = "^7.15.0"

    [tool.poetry.extras]
        testing = [
            "pytest", "pytest-xdist",
            "pytest-cov", "coverage", "coverage-conditional-plugin",
            "pytest-sugar",
            "pytest-randomly",
            "pytest-mock", "mock",
            "faker", "pytest-factoryboy",
            "pytest-benchmark",
            "pytest-profiling",
            "pytest-bdd",
            "behave",
        ]
        coverage = ["coverage", "coverage-conditional-plugin"]
        docs = [
            "sphinx", "formelsammlung", "python-dotenv", "tomlkit",
            "sphinx-rtd-theme",
            "sphinx-autodoc-typehints",
            "sphinxcontrib-apidoc",
            "sphinxcontrib-spelling",
            "sphinx-click",
            "sphinxcontrib-confluencebuilder",
        ]
        pre-commit = [
            "pre-commit", "formelsammlung",
            "rstcheck", "sphinx",
            "mypy",
            "flakehell", "flake8", "pycodestyle",
            "pylint", "pyenchant",
            "pep8-naming",
            "flake8-2020",
            "flake8-aaa",
            "flake8-annotations",
            "flake8-bandit", "bandit",
            "flake8-broken-line",
            "flake8-bugbear",
            "flake8-cognitive-complexity",
            "flake8-comprehensions",
            "flake8-docstrings",
            "flake8-eradicate",
            "flake8-logging-format",
            "flake8-mutable",
            "flake8-no-u-prefixed-strings",
            "flake8-pytest-style",
            "flake8-rst-docstrings",
            "flake8-simplify",
            "flake8-sql",
            "flake8-string-format",
            "flake8-typing-imports",
            "flake8-use-fstring",
            "flake8-variables-names",
            "flake8-walrus",
        ]
        poetry = ["poetry"]
        nox = ["nox", "tomlkit", "formelsammlung"]
        tomlkit = ["tomlkit"]
        tox = ["tox"]
        twine = ["twine"]
        safety = ["safety"]
        diff-cover = ["diff-cover"]
        sphinx-autobuild = ["sphinx-autobuild"]


#: -- BLACK CONFIG ---------------------------------------------------------------------
[tool.black]
    line-length = 88
    exclude = "venv/"
    include = '\.pyi?$'


#: -- ISORT CONFIG ---------------------------------------------------------------------
[tool.isort]
    profile = "black"
    lines_after_imports = 2
    lines_between_types = 1
    skip_gitignore = true


#: -- FLAKEHELL CONFIG -----------------------------------------------------------------
[tool.flakehell]
    format="colored"
    # show_source = true
    max_line_length = 88
    max_complexity = 20
    max_cognitive_complexity = 10
    pytest_fixture_no_parentheses = true

    [tool.flakehell.plugins]
        pylint = [
            "+*",
            #: deactivate
            "-C040?",  # spelling
            "-W0511",  # fixme
            "-C0326", "-C0330",  #: deactivated for black
            #: double checks
            "-C0301",  # same as E501[pyflakes]
            "-W0611",  # same as F401[pyflakes]
            "-W0612",  # same as F841[pyflakes]
            "-W0622",  # same as VNE003[flake8-variables-names]
            #: bugs
            "-W1203",  # Use % format in logger funcs | https://github.com/PyCQA/pylint/issues/2354
        ]
        pyflakes = [
            "+*",
            "-F821",  # same as E0602[pylint]
        ]
        mccabe = ["+*"]
        pycodestyle = [
            "+*",
            "-E203", "-W503",  #: deactivated for black
            "-E713",  #: same as SIM203[flake8-simplify]
            "-E731",  #: forbids lambda
        ]
        pep8-naming = ["+*"]
        "flake8-*" = ["+*"]
        flake8-annotations = ["+*", "-ANN101", "-ANN102"]
        flake8-bandit = ["+*", "-S322"]
        flake8-logging-format = [
            "+*",
            "-G004",  # same as W1203[pylint]
        ]
        flake8-use-fstring = ["+*", "-FS003"]

    [tool.flakehell.exceptions]
        [tool.flakehell.exceptions."tests/"]
            flake8-bandit = ["-S101"]

        [tool.flakehell.exceptions."noxfile.py"]
            flake8-cognitive-complexity = ["-CCR001"]

        [tool.flakehell.exceptions."docs/source/conf.py"]
            pylint = ["-C0103"]


#: -- PYLINT CONFIG --------------------------------------------------------------------
[tool.pylint]
    [tool.pylint.master]
        additional-builtins = "tags"

    [tool.pylint.spelling]
        spelling-dict = "en_US"
        spelling-private-dict-file = "docs/source/spelling_dict.txt"

    [tool.pylint.messages_control]
        flakehell_doesnt_get = ["E0602"]


#: -- TESTING COFIGURATION -------------------------------------------------------------
[tool._testing]
    ci_default_python_version = "3.8"
    #: Max 10 python versions are currently installed
    ci_test_python_versions = ["pypy3", "3.6", "3.7", "3.8", "3.9", "3.10.0-alpha.2 - 3.10"]
    ci_test_os = ["ubuntu", "macos", "windows"]
    cc_test_reporter_url = "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64"
    tox_skip_sdist = false  #: tox setting || Application -> true; Library -> false
    toxenv_python_versions_win32 = "py{310,39,38,37,36}"
    toxenv_python_versions_darwin = "py{py3,310,39,38,37,36}"
    toxenv_python_versions_linux = "py{py3,310,39,38,37,36}"
    toxenv_docs_builders = "test_docs-{html,linkcheck,coverage,doctest,spelling}"


#: -- PYTEST CONFIG --------------------------------------------------------------------
[tool.pytest.ini_options]
    addopts = "-ra --showlocals"
    mock_use_standalone_module = true
    junit_family = "xunit2"


#: -- COVERAGE CONFIG ------------------------------------------------------------------
[tool.coverage]
    [tool.coverage.run]
        plugins = ["coverage_conditional_plugin"]
        branch = true
        parallel = true
        context = "static-context"
#        dynamic_context = "test_function"
#        relative_files = true
        omit = [
            "tests/*",
            "docs/*",
        ]

    [tool.coverage.paths]
        tox_combine = [
            "src/python_test_cielquan",
            "*/.tox/*/lib/python*/site-packages/python_test_cielquan",
            "*/.tox/pypy*/site-packages/python_test_cielquan",
            "*/.tox\\*\\Lib\\site-packages\\python_test_cielquan",
        ]
        local_combine = [
            "src/python_test_cielquan",
            "*/.venv/lib/python*/site-packages/python_test_cielquan",
            "*/.venv\\*\\Lib\\site-packages\\python_test_cielquan",
            "*/src/python_test_cielquan",
            "*\\src\\python_test_cielquan",
        ]

    [tool.coverage.report]
        show_missing = true
        exclude_lines = [
            "# pragma: no cover",
            "if __name__ == ['\"]__main__['\"]:",
            "def __str__",
            "def __repr__",
            "if self.debug:",
            "if settings.DEBUG",
            "if 0:",
            "if False:",
            "if TYPE_CHECKING:",
            "if MYPY:",
        ]

    [tool.coverage.html]
        show_contexts = true

    [tool.coverage.coverage_conditional_plugin]
        [tool.coverage.coverage_conditional_plugin.rules]
            # use with: # pragma: <KEY>
            py-ue-36 = "sys_version_info[0:2] != (3, 6)"
            py-ue-37 = "sys_version_info[0:2] != (3, 7)"
            py-lt-38 = "sys_version_info < (3, 8)"
            py-gte-38 = "sys_version_info >= (3, 8)"


#: -- COMMITIZEN CONFIG ----------------------------------------------------------------
[tool.commitizen]
    name = "cz_conventional_commits"
    version = "0.5.2"
    tag_format = "$version"
    version_files = ["pyproject.toml:version"]


#: -- SEMANTIC-RELEASE CONFIG ----------------------------------------------------------
[tool.semantic_release]
    branch = "master"

    version_source = "commit"
    version_variable = ["pyproject.toml:tool.poetry.version"]

    commit_parser = "semantic_release.history.angular_parser"
    changelog_file = "CHANGELOG.rst"
    commit_version_number = true

    build_command = "pip install -m poetry && poetry build"
    check_build_status = true

    upload_to_pypi = true
    upload_to_release = true
