---
name: Code qualitiy


on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

  push:
    tags:
      - '!*'
    branches:
      - master

  pull_request:
    branches:
      - '**'


jobs:
  pyproject-config:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: exit 69
