---
name: Pub test


on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

  push:
    tags:
      - '!*'
    branches:
      - master

  pull_request:
    branches:
      - '**'


jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git branch -avv
      - run: git rev-parse --abbrev-ref HEAD
      - run: if [[ "${{ runner.os }}" == "ubuntu-latest" ]]; then echo yes; else echo no; fi
      - run: ${{ secrets.TEST_SECRET_RUN }}
      - run: ${{ secrets.TEST_SECRET_RUN2 }}
