name: Code qualitiy and safety

on:
  pull_request:
  push:
    branches: [master]

env:
  PYTHON_VERSION: 3.8 # CHANGE ME

jobs:
  audits:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [pre-commit, safety]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install tox
    - name: Run ${{ matrix.name }} via tox
      run: tox -e ${{ matrix.name }}
