name: Code qualitiy


env:
  default_python_version: 3.8  # CHANGE ME


on:
  push:
    tags:
      - '!*' # Do not execute on tag push
    branches:
      - master

  pull_request:
    branches:
      - '**'


jobs:
  is-merge:
    name: Is current commit a merge commit?
    runs-on: ubuntu-latest
    outputs:
      is-merge: ${{ steps.set-output.outputs.is-merge }}
      repo-name: ${{ steps.repo-dir.outputs.repo-dir }}
    steps:
      - name: Clone repo
        if: github.event_name == 'push'
        run: git clone https://github.com/${{ github.repository }}.git

      - name: Get repo dir name
        id: repo-dir
        # if: github.event_name == 'push'
        shell: bash
        run: |
          repo_dir=$(echo ${{ github.repository }} | grep -oE "\/(.*)$" | sed 's,/,,')
          echo "::set-output name=repo-dir::$repo_dir"

      - name: Checkout current branch
        if: github.event_name == 'push'
        working-directory: ${{ steps.repo-dir.outputs.repo-dir }}
        shell: bash
        run: git checkout ${GITHUB_REF#refs/heads/}

      - name: Is merge commit?
        id: is-merge
        if: github.event_name == 'push'
        working-directory: ${{ steps.repo-dir.outputs.repo-dir }}
        shell: bash
        run: |
          last_merge_commit=$(git log --merges -1 --pretty=format:"%H")
          echo "Last merge: ${last_merge_commit}"
          if [[ $last_merge_commit == ${{ github.sha }} ]]; then
            echo "::set-output name=is-merge::true"
          else
            echo "::set-output name=is-merge::false"
          fi

      - name: Set output value
        id: set-output
        shell: bash
        run: |
          if [[ ${{ github.event_name }} == 'push' ]]; then
            echo "::set-output name=is-merge::${{ steps.is-merge.outputs.is-merge }}"
          else
            echo "::set-output name=is-merge::true"
          fi


  pre-commit:
    name: tox / pre_commit
    needs: is-merge
    runs-on: ubuntu-latest
    env:
      TOXENV: pre_commit
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.default_python_version }}

      - name: Install tox
        run: |
          python -m pip install -U pip
          pip install tox

      - name: Set python version hash
        shell: bash
        run: echo "PYTHON_VERSION_SHA=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Load pre-commit/poetry cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pypoetry
          key: pre-commit|${{ env.PYTHON_VERSION_SHA }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Generate tox env
        run: tox --notest -vv --skip-missing-interpreters false

      - name: Run tox env (skip no-commit-to-branch)
        run: SKIP=no-commit-to-branch tox
        if: needs.is-merge.outputs.is-merge == 'true'

      - name: Run tox env
        run: tox
        if: needs.is-merge.outputs.is-merge == 'false'


  set-git-env-vars:
    name: Set GIT_COMMIT_SHA
    # Based on: https://github.com/paambaati/codeclimate-action/blob/master/src/main.ts#L39
    runs-on: ubuntu-latest
    outputs:
      GIT_COMMIT_SHA: ${{ steps.set-GIT_COMMIT_SHA.outputs.GIT_COMMIT_SHA }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.default_python_version }}

      - name: Get merge commit message
        id: merge-commit-msg
        shell: bash
        run: echo "::set-output name=COMMIT_MSG::$(git log --oneline -n 1 --format='%s')"
        if: github.event_name == 'pull_request'

      - name: Extract commit sha from merge commit msg
        id: merge-commit-sha
        shell: python
        run: |
          import re
          import sys
          sha = re.fullmatch(
              r"^Merge ([a-z0-9]{40}) into [a-z0-9]{40}$",
              "${{ steps.merge-commit-msg.outputs.COMMIT_MSG }}"
          )
          if sha:
              print(f"::set-output name=COMMIT_SHA::{sha.group(1)}")
          else:
              sys.exit(1)
        if: github.event_name == 'pull_request'

      - name: Set GIT_COMMIT_SHA
        id: set-GIT_COMMIT_SHA
        shell: python
        run: |
          if "${{ github.event_name }}" == "pull_request":
              sha = "${{ steps.merge-commit-sha.outputs.COMMIT_SHA }}"
              print(f"::set-output name=GIT_COMMIT_SHA::{sha}")
          else:
              print("::set-output name=GIT_COMMIT_SHA::${{ github.sha }}")


  set-status:
    name: Set status on commit
    needs: [is-merge, pre-commit, set-git-env-vars]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Set status via gihub API
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/statuses/{sha}
          owner: ${{ github.repository_owner }}
          repo: ${{ needs.is-merge.outputs.repo-name }}
          sha: ${{ needs.set-git-env-vars.outputs.GIT_COMMIT_SHA }}
          state: success
          target_url: "https://github.com/${{ github.repository }}/runs/${{ github.run_id }}"
          description: CI pipeline for code qualitiy
          context: ci-code-quality
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
