name: Dependency safety


env:
  # DO NOT FORGET TO UPDATE `skip-dependency-safety.yml` TOO !!!
  default_python_version: 3.8  # CHANGE ME


on:
  push:
    tags:
      - '!*' # Do not execute on tag push
    branches:
      - master
    paths:
      #: Dependency changes
      - 'poetry.lock'
      - 'pyproject.toml'
      #: Test config changes
      - 'noxfile.py'
      - '.github/workflows/dependency-safety.yml'

  pull_request:
    branches:
      - '**'
    paths:
      #: Dependency changes
      - 'poetry.lock'
      - 'pyproject.toml'
      #: Test config changes
      - 'noxfile.py'
      - '.github/workflows/dependency-safety.yml'


jobs:
  safety:
    name: nox / safety
    runs-on: ubuntu-latest
    env:
      NOXSESSION: safety
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.default_python_version }}

      - name: Install poetry
        run: |
          python -m pip install -U pip
          pip install poetry

      - name: Insall nox via poetry
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root --no-dev --extras nox

      - name: Generate nox session
        run: nox --install-only --verbose --error-on-missing-interpreters --forcecolor

      - name: Run nox session
        run: nox --reuse-existing-virtualenvs --forcecolor


  safety-tox:
    name: tox / safety
    runs-on: ubuntu-latest
    env:
      TOXENV: safety
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.default_python_version }}

      - name: Install tox
        run: |
          python -m pip install -U pip
          pip install tox

      - name: Generate tox env
        run: tox --notest -vv --skip-missing-interpreters false

      - name: Run tox env
        run: tox
