name: Documentation testing

on:
  pull_request:
  push:
    branches: [master]

env:
  default_python_version: 3.8 # CHANGE ME

jobs:
  doc-tests:
    name: 'Docu test: ${{ matrix.test }}'
    env:
      TOXENV: docs-test-${{ matrix.test }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [html, linkcheck, coverage, doctest] # CHANGE ME
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.default_python_version }}

      - name: Install tox
        run: |
          python -m pip install -U pip
          pip install tox

      - name: Generate tox env
        run: tox --notest -vv --skip-missing-interpreters false

      - name: 'Run sphinx builder: ${{ matrix.test }}'
        run: tox
