name: Release new version

on:
  workflow_dispatch:

env:
  default_python_version: 3.8 # CHANGE ME

jobs:
# FIXME: Add full test suit
# FIXME: Add full old test suit if not first release .. if fail and not breaking change .. fail
# TODO: for release run old tests against the current package. If they do not pass its a breaking change and if the breaking change is not in commit msg ... error


  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.default_python_version }}

    - name: Install poetry
      run: |
        python -m pip install -U pip
        pip install poetry

    # TODO: setup standard-version + poetry or https://python-semantic-release.readthedocs.io/en/latest/ ?
    # FIXME: run standard-version which does:
      # NOTE: auto version bump
      # NOTE: poetry version
      # NOTE: update changelog
      # NOTE: git tag

    # FIXME: git push --tags

    # TODO: whl for different py-ver / os ?!
    - name: Build package
      run: python -m poetry build

    - name: Publish package on test.PyPI
      # TODO: remove current upload to test.pypi
      env:
        POETRY_REPOSITORIES_TEST_URL: ${{ secrets.POETRY_REPOSITORIES_TEST_URL }}
        POETRY_HTTP_BASIC_TEST_USERNAME: ${{ secrets.POETRY_HTTP_BASIC_TEST_USERNAME }}
        POETRY_HTTP_BASIC_TEST_PASSWORD: ${{ secrets.POETRY_HTTP_BASIC_TEST_PASSWORD }}
#        POETRY_HTTP_BASIC_PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
#        POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#      run: python -m poetry publish
      run: python -m poetry publish -r test
