name: Release new version

on:
  workflow_dispatch:

env:
  default_python_version: 3.8 # CHANGE ME

jobs:
# TODO: Add full test suit:

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.default_python_version }}

    - name: Install poetry
      run: |
        python -m pip install -U pip
        pip install poetry

    - name: Build package
      run: python -m poetry build

      # TODO: remove command - current upload to test.pypi
    - name: Publish package on test.PyPI
      env:
        POETRY_REPOSITORIES_TEST_URL: ${{ secrets.POETRY_REPOSITORIES_TEST_URL }}
        POETRY_HTTP_BASIC_TEST_USERNAME: ${{ secrets.POETRY_HTTP_BASIC_TEST_USERNAME }}
        POETRY_HTTP_BASIC_TEST_PASSWORD: ${{ secrets.POETRY_HTTP_BASIC_TEST_PASSWORD }}
      run: python -m poetry publish -r test

#    - name: Publish package on PyPI
#      env:
#        POETRY_HTTP_BASIC_PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
#        POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#      run: python -m poetry publish
