on:
  workflow_dispatch:

  push:
    tags:
      - '!*' # Do not execute on tag push
    branches:
      - master

  pull_request:
    branches:
      - '**'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -ahlF --color=auto

      - uses: actions/checkout@v2

      - run: pwd
      - run: ls -ahlF --color=auto

      - id: latest-commit
        run: |
          git fetch
          git describe --abbrev=0

      - uses: actions/checkout@v2
        with:
          path: old-tests
          ref: master

      - run: ls -ahlF --color=auto
