
on:
  workflow_dispatch:

  push:
    tags:
      - '!*' # Do not execute on tag push
    branches:
      - master

  pull_request:
    branches:
      - '**'


jobs:
  test:
    runs-on: windows-latest
    steps:
      - run: ls $RUNNER_TOOL_CACHE
        shell: bash
      - run: ls $RUNNER_TOOL_CACHE/Python
        shell: bash
      - run: ls $RUNNER_TOOL_CACHE/PyPy
        shell: bash
      - run: ls $RUNNER_TOOL_CACHE/Python/3.6.8
        shell: bash
      - run: ls $RUNNER_TOOL_CACHE/Python/3.6.8/x64
        shell: bash
      - run: ls $RUNNER_TOOL_CACHE/Python/3.6.8/x64/bin
        shell: bash
      - run: ls $RUNNER_TOOL_CACHE/PyPy/3.6.8/x64/Scripts
        shell: bash
