name: Code testing

on:
  pull_request:
  push:
    branches: [master]
    tags:
      - '!*' # Do not execute on tag push

env:
  default_python_version: 3.8 # CHANGE ME
  CC_TEST_REPORTER_URL: https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64

jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.run_id }}
          echo ${{ github.run_number }}
