name: Code testing

on:
  pull_request:
  push:
    branches: [master]
    tags:
      - '!*' # Do not execute on tag push

env:
  default_python_version: 3.8 # CHANGE ME

jobs:
  set-git-env-vars:
    continue-on-error: true
    # Based on: https://github.com/paambaati/codeclimate-action/blob/master/src/main.ts#L39
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.default_python_version }}

      - name: all vars
        run: |
          echo action ${{ github.action }}
          echo action_path ${{ github.action_path }}
          echo actor ${{ github.actor }}
          echo base_ref ${{ github.base_ref }}
          echo event ${{ github.event }}
          echo event_name ${{ github.event_name }}
          echo event_path ${{ github.event_path }}
          echo head_ref ${{ github.head_ref }}
          echo job ${{ github.job }}
          echo ref ${{ github.ref }}
          echo repository ${{ github.repository }}
          echo repository_owner ${{ github.repository_owner }}
          echo run_id ${{ github.run_id }}
          echo run_number ${{ github.run_number }}
          echo sha ${{ github.sha }}
          echo workflow ${{ github.workflow }}
          echo workspace ${{ github.workspace }}

      - name: Get GIT_COMMIT_SHA for PRs
        # Based on: https://github.com/deivid-rodriguez/pry-byebug/blob/377e5b7d229a157bb896f21d776f71fc389a5c00/.github/workflows/ubuntu.yml#L46
        # https://github.com/codeclimate/test-reporter/issues/406#issuecomment-578483422
        # Does not work for external forks
        # TODO: test if works for PRs
        id: get-pr-sha
        shell: bash
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/$GITHUB_HEAD_REF:refs/remotes/origin/$GITHUB_HEAD_REF
          echo "::set-output name=GIT_COMMIT_SHA::$(git rev-parse origin/$GITHUB_HEAD_REF)"
        if: github.event_name == 'pull_request'

      - name: Set GIT_COMMIT_SHA
        id: set-GIT_COMMIT_SHA
        shell: python
        run: |
          if "${{ github.event_name }}" == "pull_request":
              sha = "${{ steps.get-pr-sha.outputs.GIT_COMMIT_SHA }}"
              print("::set-output name=GIT_COMMIT_SHA::{sha}")
          else:
              print("::set-output name=GIT_COMMIT_SHA::${{ github.sha }}")

      - name: Set GIT_BRANCH
        id: set-GIT_BRANCH
        shell: python
        run: |
          branch = "${{ github.ref }}".lstrip("refs/heads/")
          if "${{ github.event_name }}" == "pull_request":
              head_ref = "${{ github.head_ref }}"
              if head_ref:
                  branch = head_ref
          print(f"::set-output name=GIT_BRANCH::{branch}")


# NORMAL COMMIT
#action               run1
#action_path
#actor                Cielquan
#base_ref
#event                Object
#event_name           push
#event_path           /home/runner/work/_temp/_github_workflow/event.json
#head_ref
#job                  set-git-env-vars
#ref                  refs/heads/master
#repository           Cielquan/python_test-cielquan
#repository_owner     Cielquan
#run_id               347807205
#run_number           1
#sha                  2c1454a35e68227495cd6690a4f535c20c88557a
#workflow             Code testing
#workspace            /home/runner/work/python_test-cielquan/python_test-cielquan


# INTERNAL PR - test-pr
# REAL SHA f3f4e7e921805e6b2d7856f3bfd0135027a25c77
#action               run1
#action_path
#actor                Cielquan
#base_ref             master
#event                Object
#event_name           pull_request
#event_path           /home/runner/work/_temp/_github_workflow/event.json
#head_ref             test-pr
#job                  et-git-env-vars
#ref                  refs/pull/24/merge
#repository           Cielquan/python_test-cielquan
#repository_owner     Cielquan
#run_id               347817880
#run_number           2
#sha                  0fde7fc66baf3c32b92ba9dbd38fd768ef07f0ea
#workflow             Code testing
#workspace            /home/runner/work/python_test-cielquan/python_test-cielquan


# EXTERNAL PR - patch-1
# REAL SHA 9b4a25c553b9dfb07f55de402644d2236fe3984a
#action               run1
#action_path
#actor                Cielquan2
#base_ref             master
#event                Object
#event_name           pull_request
#event_path           /home/runner/work/_temp/_github_workflow/event.json
#head_ref             patch-1
#job                  set-git-env-vars
#ref                  refs/pull/25/merge
#repository           Cielquan/python_test-cielquan
#repository_owner     Cielquan
#run_id               347830264
#run_number           5
#sha                  50b281eddb961350190ac74283753550d95511a5
#workflow             Code testing
#workspace            /home/runner/work/python_test-cielquan/python_test-cielquan
