name: Test workflowception

on:
  workflow_run:
    workflows: ["Test init", "Test init2"]
#     branches: [master]
    types: 
      - completed

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
