---
name: Test


on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

  push:
    tags:
      - '!*'
    branches:
      - master

  pull_request:
    branches:
      - '**'

jobs:
  test-code-win:
    name: Test
    runs-on: windows-latest
    steps:
      - run: echo ${{ runner.os }}

  test-code-mac:
    name: Test
    runs-on: windows-latest
    steps:
      - run: echo ${{ runner.os }}

  test-code-nix:
    name: Test
    runs-on: windows-latest
    steps:
      - run: echo ${{ runner.os }}
