name: Code testing

on:
  pull_request:
  push:
    branches: [master]
    tags:
      - '!*' # Do not execute on tag push

env:
  default_python_version: 3.8 # CHANGE ME

jobs:
  set-git-env-vars:
    continue-on-error: true
    # Based on: https://github.com/paambaati/codeclimate-action/blob/master/src/main.ts#L39
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.default_python_version }}

      - name: all vars
        run: |
          echo actor ${{ github.actor }}
          echo base_ref ${{ github.base_ref }}
          echo head_ref ${{ github.head_ref }}
          echo ref ${{ github.ref }}
          echo ${GITHUB_REF}
          # Only ok for push ... NOT PRs
          echo sha ${{ github.sha }}
          echo ${GITHUB_SHA}

      - name: Get commit message from current commit
        id: commit-msg
        shell: bash
        run: echo "::set-output name=COMMIT_MSG::$(git log --oneline -n 1 --format='%s')"

      - name: Extract commit sha from commit message
        id: commit-sha
        shell: python
        run: |
          import re
          import sys
          sha = re.fullmatch(
              r"^Merge ([a-z0-9]{40}) into [a-z0-9]{40}$",
              "${{ steps.commit-msg.outputs.COMMIT_MSG }}"
          )
          if sha:
              print(f"::set-output name=COMMIT_SHA::{sha.group(1)}")
          else:
              sys.exit(1)

      - run: echo ${{ steps.commit-sha.outputs.COMMIT_SHA }}

      - name: Get GIT_COMMIT_SHA for PRs
        # Based on: https://github.com/deivid-rodriguez/pry-byebug/blob/377e5b7d229a157bb896f21d776f71fc389a5c00/.github/workflows/ubuntu.yml#L46
        # https://github.com/codeclimate/test-reporter/issues/406#issuecomment-578483422
        # Does not work for external forks
        # TODO: test if works for PRs
        id: get-pr-sha
        shell: bash
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/$GITHUB_HEAD_REF:refs/remotes/origin/$GITHUB_HEAD_REF
          echo "::set-output name=GIT_COMMIT_SHA::$(git rev-parse origin/$GITHUB_HEAD_REF)"
        if: github.event_name == 'pull_request'

      - name: Set GIT_COMMIT_SHA
        id: set-GIT_COMMIT_SHA
        shell: python
        run: |
          if "${{ github.event_name }}" == "pull_request":
              sha = "${{ steps.get-pr-sha.outputs.GIT_COMMIT_SHA }}"
              print("::set-output name=GIT_COMMIT_SHA::{sha}")
          else:
              print("::set-output name=GIT_COMMIT_SHA::${{ github.sha }}")

      - name: Set GIT_BRANCH
        id: set-GIT_BRANCH
        shell: python
        run: |
          branch = "${{ github.ref }}".lstrip("refs/heads/")
          if "${{ github.event_name }}" == "pull_request":
              head_ref = "${{ github.head_ref }}"
              if head_ref:
                  branch = head_ref
          print(f"::set-output name=GIT_BRANCH::{branch}")


# patch-1 und patch-2 sha:
# 5e4b0d60b676798dc8fa9c7e2e2fcf46e4559ef1


# NORMAL COMMIT
#actor                Cielquan
#base_ref
#head_ref
#ref                  refs/heads/master
#sha                  2c1454a35e68227495cd6690a4f535c20c88557a


# INTERNAL PR - test-pr
# REAL SHA f3f4e7e921805e6b2d7856f3bfd0135027a25c77
#actor                Cielquan
#base_ref             master
#head_ref             test-pr
#ref                  refs/pull/24/merge
#sha                  0fde7fc66baf3c32b92ba9dbd38fd768ef07f0ea


# EXTERNAL PR - patch-1
# REAL SHA 9b4a25c553b9dfb07f55de402644d2236fe3984a
#actor                Cielquan2
#base_ref             master
#head_ref             patch-1
#ref                  refs/pull/25/merge
#sha                  50b281eddb961350190ac74283753550d95511a5
