name: Test workflowception

on:
  workflow_run:
    workflows: ["Code testing"]
    branches: [master]
    types: 
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hi
      - run: echo ${{ env.CC_TEST_REPORTER_URL }}
