name: Test documentation


env:
  # DO NOT FORGET TO UPDATE `skip-test-docs.yml` TOO !!!
  default_python_version: 3.8  # CHANGE ME
  TEST_BUILDER: '[html, linkcheck, coverage, doctest, spelling]'  # CHANGE ME


on:
  push:
    tags:
      - '!*' # Do not execute on tag push
    branches:
      - master
    paths:
      #: Source changes
      - 'docs/**'
      - 'src/**/*.py'
      - 'CHANGELOG.rst'
      - 'LICENSE.txt'
      #: Dependency changes
      - 'poetry.lock'
      - 'pyproject.toml'
      #: Test config changes
      - 'tox.ini'
      - 'noxfile.py'
      - '.github/workflows/test-docs.yml'

  pull_request:
    branches:
      - '**'
    paths:
      #: Source changes
      - 'docs/**'
      - 'src/**/*.py'
      - 'CHANGELOG.rst'
      - 'LICENSE.txt'
      #: Dependency changes
      - 'poetry.lock'
      - 'pyproject.toml'
      #: Test config changes
      - 'tox.ini'
      - 'noxfile.py'
      - '.github/workflows/test-docs.yml'


jobs:
  create-builder-test-matrix:
    name: Set test matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.default_python_version }}

      - name: Parse TEST_MATRIX
        id: set-matrix
        shell: python
        run: |
          matrix = {"test": "${{ env.TEST_BUILDER }}"[1:-1].split(", ")}
          print(f"""::set-output name=matrix::{matrix}""")


  test-docs:
    name: tox / test-docs-${{ matrix.test }}
    needs: create-builder-test-matrix
    if: needs.create-builder-test-matrix.result == 'success'
    env:
      TOXENV: test-docs-${{ matrix.test }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.create-builder-test-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.default_python_version }}

      - name: Install tox
        run: |
          python -m pip install -U pip
          pip install tox

      - name: Set python version hash
        shell: bash
        run: echo "PYTHON_VERSION_SHA=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Load tox-env from cache
        uses: actions/cache@v2
        id: cache
        with:
          path: .tox/${{ env.TOXENV }}
          key: tox-env|${{ env.TOXENV }}|${{ runner.os }}|${{ env.PYTHON_VERSION_SHA }}|${{ hashFiles('**/poetry.lock') }}

      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        shell: bash
        run: timeout 10s .tox/${{ env.TOXENV }}/bin/pip --version || rm -rf .tox

      - name: Generate tox env
        run: tox --notest -vv --skip-missing-interpreters false

      - name: Run tox env
        run: tox
